### PR TITLE
process candidates in queue when state is not pending

### PR DESCRIPTION
**Pull request by xdumaine**
Problem: 

A server may have asynchronous processing/delivery on jingle session stanzas causing candidates to arrive prior to the session initiate/accept. 

Solution:

While in the pending state, do not process ice changes. Once transport info arrives in active state (no longer pending), process all ice changes in buffer.

This makes handling of transport info a little more robust and incidentally solves the problem I had in https://github.com/otalk/RTCPeerConnection/issues/67

### CODE REVIEW

**Comment by xdumaine** [comment]
Thoughts @fippo @legastero ?

**Comment by fippo** [comment]
suppose that all transport-info arrives before session-accept... (I assume this can not happen before session-initiate since this would result in unknown-session) -- do they ever get processed?

looks ok to me but I still fail to understand why your server delivers stanza out of order?

**Comment by xdumaine** [comment]
> server delivers stanzas out of order

It has to do with async state publishing to external services. I'm working on improving that, but it's a bigger lift. AFAICT, there's no requirement that they be delivered in order, since there's no explicit ordering on the stanzas themselves. If that's the case, should that be part of the spec?

> all transport-info arrives before session-accept

I'll update to handle this.

**Comment by xdumaine** [comment]
Ordering _is_ part of the spec. Closing this since it's not necessary.

**Pull request closed without merging**
