### PR TITLE
support passing constraints to accept/answer

### PR DESCRIPTION
**Pull request by xdumaine**
@legastero @fippo

### CODE REVIEW

**Comment by xdumaine** [comment]
We need to add some tests to this module...

**Comment by legastero** [comment]
LGTM

**Comment by xdumaine** [comment]
@fippo just mentioned that Chrome only supports legacy constraints for answer.. not sure what makes sense as defaults. I guess no constraints?

**Comment by xdumaine** [comment]
I decided to use the legacy constraints, since that what RTCPeerConnection module uses by default in the answer method. That way, there are no breaking changes here.

**Comment by xdumaine** [comment]
@legastero I bumped the version. Could you please publish npm update? Thanks!

**Comment by legastero** [comment]
Published, thanks!

**Pull request merged**
