### PR TITLE
add the ability to choose which tracks to swap in a stream switch

### PR DESCRIPTION
**Pull request by xdumaine**
Solves #11 by making it configurable

### CODE REVIEW

**Comment by xdumaine** [comment]
The defaults for the new opts ensure that the existing behavior is maintained with no changes required.

**Comment by legastero** [comment]
+1

**Comment by legastero** [comment]
Actually, going back through the commit history related to this, we should just drop that behaviour entirely.

The motivation was to nicely handle swapping out a camera video with a screenshare while keeping audio, but that should be handled at the application level, not here.

**Comment by xdumaine** [comment]
@legastero I'd be ok with that too, I just didn't want to break anything relying on that. If you're good with that I'll update to just remove it.

**Comment by legastero** [comment]
Closing in favor of #13

**Pull request closed without merging**
